## Start of an api doc, not for the next iteration

openapi: 3.0.0
info:
  title: API Documentation
  description: Simple Swagger demo
  version: 1.0.0
servers:
  - url: /api/
paths:
  /consumed:
    get:
      summary: Retrieve a json object of all power consumed 
      operationId: consumed
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

